spring:
 profiles: dev
gnews:
 baseurl: "https://gnews.io/"
 apikey: '${GNEWS_APIKEY}'
 topic: "technology"

management.endpoints.web.exposure.include: 'info, health, metrics, configprops, loggers'
management.endpoint.health.show-details: 'always'